---
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: Check and install packages if missing
      block:
        - name: Check if {{ item }} is installed
          command: "which {{ item }}"
          register: check_result
          ignore_errors: true

        - name: Install {{ item }} if not installed
          yum:
            name: "{{ item }}"
            state: present
          when: check_result.rc != 0
      with_items:
        - git
        - java
        - python3