---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks: 

     - name: Install Git on Host Machines
       action: yum pkg=git state=present

     - name: Install docker on hosts Machines
       action: yum pkg=docker state=present

     - name: start docker server on host Machines
       actions: service name=docker state=started

     - name: Stop the docker server on host Machines
       action: service name=docker state=stopped

     - name: Restart the docker server on host Machines
       action: service name=docker state=restarted


